export const ERROR_CODES = {
  AUTH_OTP_SEND_FAILED: 'AUTH_OTP_SEND_FAILED',
  AUTH_OTP_INVALID: 'AUTH_OTP_INVALID',
  AUTH_PASSWORD_INVALID: 'AUTH_PASSWORD_INVALID',
  AUTH_PASSWORD_NOT_SET: 'AUTH_PASSWORD_NOT_SET',
  AUTH_STAFF_NOT_ALLOWED: 'AUTH_STAFF_NOT_ALLOWED',
  AUTH_STAFF_INACTIVE: 'AUTH_STAFF_INACTIVE',
  AUTH_SESSION_REQUIRED: 'AUTH_SESSION_REQUIRED',
  AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
  AUTH_SESSION_INVALID: 'AUTH_SESSION_INVALID',
  AUTH_SESSION_REVOKED: 'AUTH_SESSION_REVOKED',
  AUTH_STAFF_2FA_REQUIRED: 'AUTH_STAFF_2FA_REQUIRED',
  AUTH_SIGN_UP_USE_SIGN_IN: 'AUTH_SIGN_UP_USE_SIGN_IN',
  AUTH_SIGN_IN_USE_SIGN_UP: 'AUTH_SIGN_IN_USE_SIGN_UP',

  PERMISSION_DENIED: 'PERMISSION_DENIED',
  PERMISSION_ROLE_REQUIRED: 'PERMISSION_ROLE_REQUIRED',
  PERMISSION_CAPABILITY_REQUIRED: 'PERMISSION_CAPABILITY_REQUIRED',

  VALIDATION_INVALID_INPUT: 'VALIDATION_INVALID_INPUT',
  VALIDATION_INVALID_PHONE: 'VALIDATION_INVALID_PHONE',
  VALIDATION_INVALID_EMAIL: 'VALIDATION_INVALID_EMAIL',
  VALIDATION_INVALID_URL: 'VALIDATION_INVALID_URL',
  VALIDATION_INVALID_LOCALE: 'VALIDATION_INVALID_LOCALE',

  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_CONFLICT: 'RESOURCE_CONFLICT',
  RESOURCE_GONE: 'RESOURCE_GONE',

  BUSINESS_NOT_VIP: 'BUSINESS_NOT_VIP',
  BUSINESS_ALREADY_ACTIVE: 'BUSINESS_ALREADY_ACTIVE',
  BUSINESS_INVALID_STATUS_TRANSITION: 'BUSINESS_INVALID_STATUS_TRANSITION',
  BUSINESS_CATEGORY_HIGH_RISK: 'BUSINESS_CATEGORY_HIGH_RISK',
  BUSINESS_CITY_COUNTRY_MISMATCH: 'BUSINESS_CITY_COUNTRY_MISMATCH',

  VIP_REQUIRED: 'VIP_REQUIRED',
  VIP_SUBSCRIPTION_INACTIVE: 'VIP_SUBSCRIPTION_INACTIVE',

  CARD_NOT_FOUND: 'CARD_NOT_FOUND',
  CARD_ALREADY_ACTIVE: 'CARD_ALREADY_ACTIVE',
  CARD_INVALID_STATUS_TRANSITION: 'CARD_INVALID_STATUS_TRANSITION',

  INTRODUCTION_NOT_ALLOWED: 'INTRODUCTION_NOT_ALLOWED',
  INTRODUCTION_TARGET_UNAVAILABLE: 'INTRODUCTION_TARGET_UNAVAILABLE',
  INTRODUCTION_PENDING_EXISTS: 'INTRODUCTION_PENDING_EXISTS',
  INTRODUCTION_INVALID_STATUS_TRANSITION: 'INTRODUCTION_INVALID_STATUS_TRANSITION',

  FEATURED_LIMIT_REACHED: 'FEATURED_LIMIT_REACHED',
  FEATURED_BUSINESS_NOT_PUBLISHED: 'FEATURED_BUSINESS_NOT_PUBLISHED',

  RATE_LIMITED: 'RATE_LIMITED',
  RATE_LIMIT_INTRODUCTION_DAILY: 'RATE_LIMIT_INTRODUCTION_DAILY',
  RATE_LIMIT_INTRODUCTION_TARGET: 'RATE_LIMIT_INTRODUCTION_TARGET',

  SERVER_ERROR: 'SERVER_ERROR',
  SERVER_DEPENDENCY_UNAVAILABLE: 'SERVER_DEPENDENCY_UNAVAILABLE',
  SERVER_STRIPE_WEBHOOK_INVALID: 'SERVER_STRIPE_WEBHOOK_INVALID',
  STRIPE_CONFIG_MISSING: 'STRIPE_CONFIG_MISSING',
  CHECKOUT_CREATION_FAILED: 'CHECKOUT_CREATION_FAILED',
  BUSINESS_NOT_APPROVED: 'BUSINESS_NOT_APPROVED',
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
