export const STAFF_ROLES = ['OWNER', 'ADMIN', 'MODERATOR'] as const;
export type StaffRole = (typeof STAFF_ROLES)[number];

export const STAFF_ROLE_RANK = {
  OWNER: 3,
  ADMIN: 2,
  MODERATOR: 1,
} as const satisfies Record<StaffRole, number>;

export const STAFF_PERMISSIONS = {
  DASHBOARD_METRICS_READ: 'DASHBOARD_METRICS_READ',
  USERS_READ: 'USERS_READ',
  USERS_BLOCK: 'USERS_BLOCK',
  CARDS_READ: 'CARDS_READ',
  CARDS_REISSUE: 'CARDS_REISSUE',
  CARDS_REVOKE: 'CARDS_REVOKE',
  SUBSCRIPTIONS_READ: 'SUBSCRIPTIONS_READ',
  SUBSCRIPTIONS_CANCEL_ADMIN: 'SUBSCRIPTIONS_CANCEL_ADMIN',
  BUSINESSES_MODERATE: 'BUSINESSES_MODERATE',
  INTRODUCTIONS_MODERATE: 'INTRODUCTIONS_MODERATE',
  TAXONOMY_MANAGE: 'TAXONOMY_MANAGE',
  FEATURED_BUSINESSES_MANAGE: 'FEATURED_BUSINESSES_MANAGE',
  STRIPE_PRICES_MANAGE: 'STRIPE_PRICES_MANAGE',
  STAFF_MANAGE: 'STAFF_MANAGE',
  AUDIT_READ: 'AUDIT_READ',
  INTERNAL_NOTES_CREATE: 'INTERNAL_NOTES_CREATE',
} as const;

export type StaffPermission = (typeof STAFF_PERMISSIONS)[keyof typeof STAFF_PERMISSIONS];

export const STAFF_ROLE_PERMISSIONS = {
  OWNER: [
    STAFF_PERMISSIONS.DASHBOARD_METRICS_READ,
    STAFF_PERMISSIONS.USERS_READ,
    STAFF_PERMISSIONS.USERS_BLOCK,
    STAFF_PERMISSIONS.CARDS_READ,
    STAFF_PERMISSIONS.CARDS_REISSUE,
    STAFF_PERMISSIONS.CARDS_REVOKE,
    STAFF_PERMISSIONS.SUBSCRIPTIONS_READ,
    STAFF_PERMISSIONS.SUBSCRIPTIONS_CANCEL_ADMIN,
    STAFF_PERMISSIONS.BUSINESSES_MODERATE,
    STAFF_PERMISSIONS.INTRODUCTIONS_MODERATE,
    STAFF_PERMISSIONS.TAXONOMY_MANAGE,
    STAFF_PERMISSIONS.FEATURED_BUSINESSES_MANAGE,
    STAFF_PERMISSIONS.STRIPE_PRICES_MANAGE,
    STAFF_PERMISSIONS.STAFF_MANAGE,
    STAFF_PERMISSIONS.AUDIT_READ,
    STAFF_PERMISSIONS.INTERNAL_NOTES_CREATE,
  ],
  ADMIN: [
    STAFF_PERMISSIONS.DASHBOARD_METRICS_READ,
    STAFF_PERMISSIONS.USERS_READ,
    STAFF_PERMISSIONS.USERS_BLOCK,
    STAFF_PERMISSIONS.CARDS_READ,
    STAFF_PERMISSIONS.CARDS_REISSUE,
    STAFF_PERMISSIONS.CARDS_REVOKE,
    STAFF_PERMISSIONS.SUBSCRIPTIONS_READ,
    STAFF_PERMISSIONS.SUBSCRIPTIONS_CANCEL_ADMIN,
    STAFF_PERMISSIONS.BUSINESSES_MODERATE,
    STAFF_PERMISSIONS.INTRODUCTIONS_MODERATE,
    STAFF_PERMISSIONS.TAXONOMY_MANAGE,
    STAFF_PERMISSIONS.FEATURED_BUSINESSES_MANAGE,
    STAFF_PERMISSIONS.STAFF_MANAGE,
    STAFF_PERMISSIONS.AUDIT_READ,
    STAFF_PERMISSIONS.INTERNAL_NOTES_CREATE,
  ],
  MODERATOR: [
    STAFF_PERMISSIONS.DASHBOARD_METRICS_READ,
    STAFF_PERMISSIONS.SUBSCRIPTIONS_READ,
    STAFF_PERMISSIONS.BUSINESSES_MODERATE,
    STAFF_PERMISSIONS.INTRODUCTIONS_MODERATE,
    STAFF_PERMISSIONS.TAXONOMY_MANAGE,
    STAFF_PERMISSIONS.FEATURED_BUSINESSES_MANAGE,
    STAFF_PERMISSIONS.INTERNAL_NOTES_CREATE,
  ],
} as const satisfies Record<StaffRole, readonly StaffPermission[]>;

export const MEMBER_CAPABILITIES = {
  DIGITAL_CARD_READ: 'DIGITAL_CARD_READ',
  DIRECTORY_READ: 'DIRECTORY_READ',
  VIP_UPGRADE: 'VIP_UPGRADE',
  VIP_SUBSCRIPTION_MANAGE: 'VIP_SUBSCRIPTION_MANAGE',
  BUSINESS_SUBMIT: 'BUSINESS_SUBMIT',
  BUSINESS_MANAGE_OWN: 'BUSINESS_MANAGE_OWN',
  INTRODUCTIONS_SUBMIT: 'INTRODUCTIONS_SUBMIT',
} as const;

export type MemberCapability = (typeof MEMBER_CAPABILITIES)[keyof typeof MEMBER_CAPABILITIES];

export const MEMBER_DASHBOARD_TABS = [
  'account',
  'catalog',
  'subscription',
  'business',
  'introductions',
  'settings',
  'details',
  'card',
  'audit',
  'permissions',
] as const;

export type MemberDashboardTab = (typeof MEMBER_DASHBOARD_TABS)[number];

export type UserContext = {
  isVip: boolean;
  hasBusiness: boolean;
  businessPublished: boolean;
};
